apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashy
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashy
  template:
    metadata:
      labels:
        app: crashy
    spec:
      containers:
      - name: crashy
        image: busybox:1.36
        command: ["sh","-c","echo starting && sleep 2 && exit 1"]
